#include <ogc/system.h>
#include "dwc.h"

const struct DWC_PatchList dwcPatchOptions[NUM_OF_SERVERS] = {
	[SERVER_WIIMMFI] = {
		.base_url="wiimmfi.de",
		.naswii_url="naswii.wiimmfi.de/ac",
		.conntest_url="conntest.wiimmfi.de",
		.pr_url="naswii.wiimmfi.de/pr",
		.dls_url="dls1.wiimmfi.de",
		.gamespy_url="gs.wiimmfi.de",
		.req_method="http://",
		.dns="8.8.8.8",
		.title="Wiimmfi (default)",
	},
	[SERVER_TEST_WIIMMFI] = {
		.base_url="test.wiimmfi.de",
		.naswii_url="naswii.test.wiimmfi.de/ac",
		.conntest_url="conntest.test.wiimmfi.de",
		.pr_url="naswii.test.wiimmfi.de/pr",
		.dls_url="dls1.test.wiimmfi.de",
		.gamespy_url="gs.test.wiimmfi.de",
		.req_method="http://",
		.dns="8.8.8.8",
		.title="Wiimmfi Test Server",
	},
	[SERVER_ALTWFC] = {
		.base_url="nintendowifi.net",
		.naswii_url="naswii.nintendowifi.net/ac",
		.conntest_url="conntest.nintendowifi.net",
		.pr_url="naswii.nintendowifi.net/pr",
		.dls_url="dls1.nintendowifi.net",
		.gamespy_url="gs.nintendowifi.net",
		.req_method="http://",
		.dns="104.131.93.87",
		.title="AltWFC",
	},
/*	[SERVER_LUMAFI] = {
		.base_url="lumafi.tk",
		.naswii_url="naswii.lumafi.tk/ac",
		.conntest_url="conntest.lumafi.tk",
		.pr_url="naswii.lumafi.tk/pr",
		.dls_url="dls1.lumafi.tk",
		.gamespy_url="gs.lumafi.tk",
		.req_method="http://",
		.dns="8.8.8.8",
		.title="Lumafi (not operational yet!)",
	},
*/
	[SERVER_NOSSL] = {
		.base_url="nintendowifi.net",
		.naswii_url="naswii.nintendowifi.net/ac",
		.conntest_url="conntest.nintendowifi.net",
		.pr_url="naswii.nintendowifi.net/pr",
		.dls_url="dls1.nintendowifi.net",
		.gamespy_url="gs.nintendowifi.net",
		.req_method="http://",
		.dns="8.8.8.8",
		.title="No SSL (only for testing)",
	},
	[SERVER_NOPATCHES] = {
		.base_url="nintendowifi.net",
		.naswii_url="naswii.nintendowifi.net/ac",
		.conntest_url="conntest.nintendowifi.net",
		.pr_url="naswii.nintendowifi.net/pr",
		.dls_url="dls1.nintendowifi.net",
		.gamespy_url="gs.nintendowifi.net",
		.req_method="https://",
		.dns="8.8.8.8",
		.title="No Patches",
	},
};
